apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: caikit-tgis-serving-28
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: caikit-tgis-serving-28
    app.kubernetes.io/part-of: caikit-tgis-serving
  name: caikit-tgis-serving-28
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: caikit-tgis-serving-28
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: caikit-tgis-serving-28
    spec:
      containers:
      - image: quay.io/modh/caikit-tgis-serving@sha256:6ad9021a92925759490991446a6a2453bdfeed9e3d32146915c0a7984a2df24c
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
